account:
  #用户名
  username: 
  #密码
  password: 

pa: 11

ruokuai:
  # 在这填“若快”账号的用户名
  username: 
  # 在这填“若快”账号的密码
  password: 

ticket:
  train_date: 2019-01-30
  from_station: BJP
  to_station: YIJ
  station_trains: Z277
  set_type:
    - "硬卧"
    - "软卧"
