import per.solax.gradle.GradleExec;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "启动.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        GradleExec gradleExec = new GradleExec();
        gradleExec.run();
    }
}
